---
apiVersion: v2
name: jaeger-exporter
description:
  The Jaeger Exporter creates the Prometheus metrics for the Service Performance
  Monitoring.
type: application
version: 1.1.0
appVersion: v0.8.0
